// <auto-generated />
using System;
using LZMotel.Local.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LZMotel.Local.API.Migrations
{
    [DbContext(typeof(LocalContext))]
    [Migration("20201209025503_LocalSuite")]
    partial class LocalSuite
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LZMotel.Local.API.Models.Suite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Comanda")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<int>("SuiteNumero")
                        .HasColumnType("integer");

                    b.Property<int>("SuiteTransferida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SuiteNumero")
                        .IsUnique();

                    b.ToTable("Suite");
                });
#pragma warning restore 612, 618
        }
    }
}
